// @generated
// This file is autogenerated from `todoRoutes.json`, do not edit manually.

@inline
let routeName = "Root__Todos"

@inline
let routePattern = "/todos"

@live
let makeLink = (~showAll: option<bool>=?, ()) => {
  open RelayRouter.Bindings
  let queryParams = QueryParams.make()
  switch showAll {
    | None => ()
    | Some(showAll) => queryParams->QueryParams.setParam(~key="showAll", ~value=string_of_bool(showAll))
  }
  RelayRouter.Types.AppRoute({
    routePattern, 
    url: `/todos${queryParams->QueryParams.toString}`
  })
}

@live
let isRouteActive = (~exact: bool=false, {pathname}: RelayRouter.History.location): bool => {
  RelayRouter.Internal.matchPathWithOptions({"path": routePattern, "end": exact}, pathname)->Belt.Option.isSome
}

@live
let useIsRouteActive = (~exact=false, ()) => {
  let location = RelayRouter.Utils.useLocation()
  React.useMemo2(() => location->isRouteActive(~exact), (location, exact))
}
@live
type subRoute = [#Single]

@live
let useActiveSubRoute = (): option<[#Single]> => {
  let location = RelayRouter.Utils.useLocation()
  React.useMemo1(() => {
    let {pathname} = location
    if RelayRouter.Internal.matchPath("/todos/:todoId", pathname)->Belt.Option.isSome {
      Some(#Single)
    } else {
      None
    }
  }, [location])
}

@live
type prepareProps = {
  environment: RescriptRelay.Environment.t,
  location: RelayRouter.History.location,
  showAll: option<bool>,
}

let makeRouteKey = (
  ~pathParams: Js.Dict.t<string>,
  ~queryParams: RelayRouter.Bindings.QueryParams.t
): string => {
  ignore(pathParams)

  "Root__Todos:"

    ++ queryParams->RelayRouter.Bindings.QueryParams.getParamByKey("showAll")->Belt.Option.getWithDefault("")
}

@live
let makePrepareProps = (. 
  ~environment: RescriptRelay.Environment.t,
  ~pathParams: Js.Dict.t<string>,
  ~queryParams: RelayRouter.Bindings.QueryParams.t,
  ~location: RelayRouter.History.location,
): prepareProps => {
  ignore(pathParams)
  {
    environment: environment,

    location: location,
    showAll: queryParams->RelayRouter.Bindings.QueryParams.getParamByKey("showAll")->Belt.Option.flatMap(value => switch value {
      | "true" => Some(true)
      | "false" => Some(false)
      | _ => None
      }),
  }
}

@live
type renderProps<'prepared> = {
  childRoutes: React.element,
  prepared: 'prepared,
  environment: RescriptRelay.Environment.t,
  location: RelayRouter.History.location,
  showAll: option<bool>,
}

@live
type renderers<'prepared> = {
  prepare: prepareProps => 'prepared,
  prepareCode: option<(. prepareProps) => array<RelayRouter.Types.preloadAsset>>,
  render: renderProps<'prepared> => React.element,
}

@obj
external makeRenderer: (
  ~prepare: prepareProps => 'prepared,
  ~prepareCode: prepareProps => array<RelayRouter.Types.preloadAsset>=?,
  ~render: renderProps<'prepared> => React.element,
  unit
) => renderers<'prepared> = ""

type queryParams = {
  showAll: option<bool>,
}

@live
let parseQueryParams = (search: string): queryParams => {
  open RelayRouter.Bindings
  let queryParams = QueryParams.parse(search)
  {
    showAll: queryParams->QueryParams.getParamByKey("showAll")->Belt.Option.flatMap(value => switch value {
      | "true" => Some(true)
      | "false" => Some(false)
      | _ => None
      }),

  }
}

@live
let makeQueryParams = (
  ~showAll: option<bool>=?, 
  ()
) => {
  showAll: showAll,
}

@live
let setQueryParams = (
  newParams: queryParams,
  ~currentSearch: string, 
  ~navigationMode_=RelayRouter.Types.Push,
  ~removeNotControlledParams=true,
  ~history: RelayRouter.History.t,
  ()
) => {
  open RelayRouter.Bindings

  let queryParams = if removeNotControlledParams {
    QueryParams.make()
  } else {
    QueryParams.parse(currentSearch)
  }

  
  queryParams->QueryParams.setParamOpt(~key="showAll", ~value=newParams.showAll->Belt.Option.map(showAll => string_of_bool(showAll)))
  
  queryParams->RelayRouter.Internal.setQueryParams(navigationMode_, history)
}

@live
type useQueryParamsReturn = {
  queryParams: queryParams,
  setParams: (
    ~setter: queryParams => queryParams,
    ~onAfterParamsSet: queryParams => unit=?,
    ~navigationMode_: RelayRouter.Types.setQueryParamsMode=?,
    ~removeNotControlledParams: bool=?,
    unit
  ) => unit
}

@live
let useQueryParams = (): useQueryParamsReturn => {
  let {history} = RelayRouter.useRouterContext()
  let {search} = RelayRouter.Utils.useLocation()
  let currentQueryParams = React.useMemo1(() => {
    search->parseQueryParams
  }, [search])

  let searchRef = React.useRef(search)
  let currentQueryParamsRef = React.useRef(currentQueryParams)

  searchRef.current = search
  currentQueryParamsRef.current = currentQueryParams

  {
    queryParams: currentQueryParams, 
    setParams: 
      React.useMemo0(
        () => (
          ~setter,
          ~onAfterParamsSet=?,
          ~navigationMode_=RelayRouter.Types.Push,
          ~removeNotControlledParams=true,
          ()
        ) => {
          let newParams = setter(currentQueryParamsRef.current)

          switch onAfterParamsSet {
            | None => ()
            | Some(onAfterParamsSet) => onAfterParamsSet(newParams)
          }

          newParams
            ->setQueryParams(
              ~currentSearch=searchRef.current, 
              ~navigationMode_, 
              ~removeNotControlledParams, 
              ~history, 
              ()
            )
          },
      )
  }
}