// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as RelayRouterLink from "../../../router/RelayRouterLink.mjs";
import * as Route__Root__Users_route from "./__generated__/Route__Root__Users_route.mjs";
import * as Route__Root__Users__Single_route from "./__generated__/Route__Root__Users__Single_route.mjs";

var renderer = {
  prepare: (function (param) {
      console.log("preparing...!");
      return {
              someTest: true,
              dispose: (function () {
                  console.log("doing dispose");
                  
                }),
              nested: {
                dispose: (function () {
                    console.log("doing nested dispose");
                    
                  })
              }
            };
    }),
  render: (function (props) {
      var match = Route__Root__Users_route.useQueryParams(undefined);
      var setParams = match.setParams;
      var search = props.search;
      return React.createElement("div", {
                  style: {
                    backgroundColor: "tomato",
                    display: "flex",
                    height: "1500px",
                    paddingBottom: "100px",
                    alignItems: "flex-end"
                  }
                }, search !== undefined ? search : "no seearch", React.createElement(RelayRouterLink.make, {
                      to_: Route__Root__Users__Single_route.makeLink("123", undefined, undefined, undefined),
                      children: "To a user"
                    }), React.createElement("button", {
                      onClick: (function (param) {
                          return Curry._5(setParams, (function (current) {
                                        return {
                                                search: String(Math.random()),
                                                count: current.count
                                              };
                                      }), undefined, undefined, undefined, undefined);
                        })
                    }, "Set search"), props.childRoutes);
    })
};

export {
  renderer ,
  
}
/* react Not a pure module */
