// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RelayRouter from "../../../router/RelayRouter.mjs";
import * as RelayRouterLink from "../../../router/RelayRouterLink.mjs";
import * as Route__Root__Users_route from "./__generated__/Route__Root__Users_route.mjs";

function loadReactComponent(param) {
  var __x = import("@rescriptModule/SingleUser");
  return __x.then(function (m) {
              return Promise.resolve({
                          default: m.make
                        });
            });
}

function eagerPreload(param) {
  import("@rescriptModule/SingleUser");
  
}

function preload(param) {
  return {
          TAG: /* Component */0,
          moduleName: "SingleUser",
          chunk: "@rescriptModule/SingleUser",
          eagerPreloadFn: eagerPreload
        };
}

var unsafePlaceholder = {};

function makeProps(prim0, prim1, prim2) {
  var tmp = {
    id: prim0
  };
  if (prim1 !== undefined) {
    tmp.key = prim1;
  }
  return tmp;
}

var component = React.lazy(loadReactComponent);

function make(props) {
  RelayRouter.useRegisterPreloadedAsset({
        TAG: /* Component */0,
        moduleName: "SingleUser",
        chunk: "@rescriptModule/SingleUser",
        eagerPreloadFn: eagerPreload
      });
  return React.createElement(component, props);
}

var SingleUser = {
  loadReactComponent: loadReactComponent,
  eagerPreload: eagerPreload,
  preload: preload,
  UnsafePlaceholder: unsafePlaceholder,
  makeProps: makeProps,
  component: component,
  make: make
};

var renderer = {
  prepare: (function (param) {
      
    }),
  prepareCode: (function (param) {
      return [{
                TAG: /* Component */0,
                moduleName: "SingleUser",
                chunk: "@rescriptModule/SingleUser",
                eagerPreloadFn: eagerPreload
              }];
    }),
  render: (function (props) {
      return React.createElement("div", {
                  style: {
                    height: "600px"
                  }
                }, props.userId, React.createElement(make, {
                      id: props.userId
                    }), React.createElement(RelayRouterLink.make, {
                      to_: Route__Root__Users_route.makeLink(undefined, undefined, undefined),
                      preloadData: /* OnIntent */2,
                      preloadCode: /* OnInView */3,
                      children: "to overview"
                    }));
    })
};

export {
  SingleUser ,
  renderer ,
  
}
/* component Not a pure module */
