// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RelayRouter from "../../../router/RelayRouter.mjs";

function loadReactComponent(param) {
  var __x = import("@rescriptModule/TodosList");
  return __x.then(function (m) {
              return Promise.resolve({
                          default: m.make
                        });
            });
}

function eagerPreload(param) {
  import("@rescriptModule/TodosList");
  
}

function preload(param) {
  return {
          TAG: /* Component */0,
          moduleName: "TodosList",
          chunk: "@rescriptModule/TodosList",
          eagerPreloadFn: eagerPreload
        };
}

var unsafePlaceholder = {};

function makeProps(prim0, prim1) {
  var tmp = {};
  if (prim0 !== undefined) {
    tmp.key = prim0;
  }
  return tmp;
}

var component = React.lazy(loadReactComponent);

function make(props) {
  RelayRouter.useRegisterPreloadedAsset({
        TAG: /* Component */0,
        moduleName: "TodosList",
        chunk: "@rescriptModule/TodosList",
        eagerPreloadFn: eagerPreload
      });
  return React.createElement(component, props);
}

var TodosList = {
  loadReactComponent: loadReactComponent,
  eagerPreload: eagerPreload,
  preload: preload,
  UnsafePlaceholder: unsafePlaceholder,
  makeProps: makeProps,
  component: component,
  make: make
};

var renderer = {
  prepare: (function (param) {
      
    }),
  prepareCode: (function (param) {
      return [{
                TAG: /* Component */0,
                moduleName: "TodosList",
                chunk: "@rescriptModule/TodosList",
                eagerPreloadFn: eagerPreload
              }];
    }),
  render: (function (param) {
      return React.createElement(make, {});
    })
};

export {
  TodosList ,
  renderer ,
  
}
/* component Not a pure module */
