// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RelayRouterLink from "../../../router/RelayRouterLink.mjs";
import * as RelayRouterScroll from "../../../router/RelayRouterScroll.mjs";
import * as Route__Root__Users_route from "./__generated__/Route__Root__Users_route.mjs";

var renderer = {
  prepare: (function (param) {
      
    }),
  render: (function (props) {
      var mainContainerRef = React.useRef(null);
      return React.createElement(RelayRouterScroll.TargetScrollElement.Provider.make, {
                  id: "main-scroll-area",
                  targetElementRef: mainContainerRef,
                  children: React.createElement("main", {
                        ref: mainContainerRef,
                        style: {
                          height: "80vh",
                          overflowY: "auto"
                        }
                      }, React.createElement(RelayRouterLink.make, {
                            to_: Route__Root__Users_route.makeLink(undefined, 123, undefined),
                            children: "To users overview"
                          }), props.childRoutes, React.createElement(RelayRouterScroll.ScrollRestoration.make, {}))
                });
    })
};

export {
  renderer ,
  
}
/* react Not a pure module */
