// Generated by ReScript, PLEASE EDIT WITH CARE


var renderer = {
  prepare: (function (param) {
      
    }),
  render: (function (param) {
      return null;
    })
};

export {
  renderer ,
  
}
/* No side effect */
