// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RelayEnv from "../RelayEnv.mjs";
import * as RelayRouter from "../../router/RelayRouter.mjs";
import * as RouteDeclarations from "./routes/__generated__/RouteDeclarations.mjs";

var match = RelayRouter.Router.make(RouteDeclarations.make(undefined, undefined), RelayRouter.RouterEnvironment.makeBrowserEnvironment(undefined), RelayEnv.environment);

var routerContext = match[1];

export {
  routerContext ,
  
}
/* match Not a pure module */
