// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RelayRouter__Bindings from "./RelayRouter__Bindings.mjs";

function setQueryParams(queryParams, mode, history) {
  if (mode) {
    history.replace(RelayRouter__Bindings.QueryParams.toString(queryParams));
  } else {
    history.push(RelayRouter__Bindings.QueryParams.toString(queryParams));
  }
  
}

var extractDisposables = (function extractDisposables_(s, disposables = []) {
  if (s == null) {
    return disposables;
  }

  if (Array.isArray(s)) {
    s.forEach(function (o) {
      extractDisposables_(o, disposables);
    });
    return disposables;
  } 

  if (typeof s === "object") {
    if ( 
      s.hasOwnProperty("dispose") && 
      typeof s.dispose === "function"
    ) {
      disposables.push(s.dispose);
    }

    Object.keys(s).forEach(function (key) {
      var o = s[key];
      extractDisposables_(o, disposables);
    })
  }

  return disposables;
});

export {
  setQueryParams ,
  extractDisposables ,
  
}
/* No side effect */
