// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ReactRouter from "react-router";
import * as RelayRouterUtils from "../../../../router/RelayRouterUtils.mjs";

function makeLink(param) {
  return "/";
}

function isRouteActive(param, $staropt$star, param$1) {
  var exact = $staropt$star !== undefined ? $staropt$star : false;
  return Belt_Option.isSome(Caml_option.nullable_to_opt(ReactRouter.matchPath({
                      path: "/",
                      end: exact
                    }, param.pathname)));
}

function useIsRouteActive(exactOpt, param) {
  var exact = exactOpt !== undefined ? exactOpt : false;
  var $$location = RelayRouterUtils.useLocation(undefined);
  return React.useMemo((function () {
                return isRouteActive($$location, exact, undefined);
              }), [$$location]);
}

function useActiveSubRoute(param) {
  var $$location = RelayRouterUtils.useLocation(undefined);
  return React.useMemo((function () {
                var pathname = $$location.pathname;
                if (Belt_Option.isSome(Caml_option.nullable_to_opt(ReactRouter.matchPath("/todos", pathname)))) {
                  return "Todos";
                } else if (Belt_Option.isSome(Caml_option.nullable_to_opt(ReactRouter.matchPath("/users", pathname)))) {
                  return "Users";
                } else {
                  return ;
                }
              }), [$$location]);
}

function makeRouteKey(pathParams, queryParams) {
  return "Root:";
}

function makePrepareProps(environment, pathParams, queryParams, $$location) {
  return {
          environment: environment,
          location: $$location
        };
}

export {
  makeLink ,
  isRouteActive ,
  useIsRouteActive ,
  useActiveSubRoute ,
  makeRouteKey ,
  makePrepareProps ,
  
}
/* react Not a pure module */
