// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as RelayRouter from "../../../../router/RelayRouter.mjs";
import * as ReactRouter from "react-router";
import * as RelayRouterUtils from "../../../../router/RelayRouterUtils.mjs";
import * as RelayRouter__Bindings from "../../../../router/RelayRouter__Bindings.mjs";
import * as RelayRouter__Internal from "../../../../router/RelayRouter__Internal.mjs";

function makeLink(search, count, param) {
  var queryParams = RelayRouter__Bindings.QueryParams.make(undefined);
  if (search !== undefined) {
    RelayRouter__Bindings.QueryParams.setParam(queryParams, "search", encodeURIComponent(search));
  }
  if (count !== undefined) {
    RelayRouter__Bindings.QueryParams.setParam(queryParams, "count", String(count));
  }
  return "/users" + RelayRouter__Bindings.QueryParams.toString(queryParams);
}

function isRouteActive(param, $staropt$star, param$1) {
  var exact = $staropt$star !== undefined ? $staropt$star : false;
  return Belt_Option.isSome(Caml_option.nullable_to_opt(ReactRouter.matchPath({
                      path: "/users",
                      end: exact
                    }, param.pathname)));
}

function useIsRouteActive(exactOpt, param) {
  var exact = exactOpt !== undefined ? exactOpt : false;
  var $$location = RelayRouterUtils.useLocation(undefined);
  return React.useMemo((function () {
                return isRouteActive($$location, exact, undefined);
              }), [$$location]);
}

function useActiveSubRoute(param) {
  var $$location = RelayRouterUtils.useLocation(undefined);
  return React.useMemo((function () {
                if (Belt_Option.isSome(Caml_option.nullable_to_opt(ReactRouter.matchPath("/users/:userId", $$location.pathname)))) {
                  return "Single";
                }
                
              }), [$$location]);
}

function makeRouteKey(pathParams, queryParams) {
  return "Root__Users:" + Belt_Option.getWithDefault(RelayRouter__Bindings.QueryParams.getParamByKey(queryParams, "search"), "") + Belt_Option.getWithDefault(RelayRouter__Bindings.QueryParams.getParamByKey(queryParams, "count"), "");
}

function makePrepareProps(environment, pathParams, queryParams, $$location) {
  return {
          environment: environment,
          location: $$location,
          search: Belt_Option.flatMap(RelayRouter__Bindings.QueryParams.getParamByKey(queryParams, "search"), (function (value) {
                  return decodeURIComponent(value);
                })),
          count: Belt_Option.flatMap(RelayRouter__Bindings.QueryParams.getParamByKey(queryParams, "count"), Belt_Int.fromString)
        };
}

function parseQueryParams(search) {
  var queryParams = RelayRouter__Bindings.QueryParams.parse(search);
  return {
          search: Belt_Option.flatMap(RelayRouter__Bindings.QueryParams.getParamByKey(queryParams, "search"), (function (value) {
                  return decodeURIComponent(value);
                })),
          count: Belt_Option.flatMap(RelayRouter__Bindings.QueryParams.getParamByKey(queryParams, "count"), Belt_Int.fromString)
        };
}

function makeQueryParams(search, count, param) {
  return {
          search: search,
          count: count
        };
}

function setQueryParams(newParams, currentSearch, navigationMode_Opt, removeNotControlledParamsOpt, history, param) {
  var navigationMode_ = navigationMode_Opt !== undefined ? navigationMode_Opt : /* Push */0;
  var removeNotControlledParams = removeNotControlledParamsOpt !== undefined ? removeNotControlledParamsOpt : true;
  var queryParams = removeNotControlledParams ? RelayRouter__Bindings.QueryParams.make(undefined) : RelayRouter__Bindings.QueryParams.parse(currentSearch);
  RelayRouter__Bindings.QueryParams.setParamOpt(queryParams, "search", Belt_Option.map(newParams.search, (function (search) {
              return encodeURIComponent(search);
            })));
  RelayRouter__Bindings.QueryParams.setParamOpt(queryParams, "count", Belt_Option.map(newParams.count, (function (count) {
              return String(count);
            })));
  return RelayRouter__Internal.setQueryParams(queryParams, navigationMode_, history);
}

function useQueryParams(param) {
  var match = RelayRouter.useRouterContext(undefined);
  var history = match.history;
  var match$1 = RelayRouterUtils.useLocation(undefined);
  var search = match$1.search;
  var currentQueryParams = React.useMemo((function () {
          return parseQueryParams(search);
        }), [search]);
  var searchRef = React.useRef(search);
  var currentQueryParamsRef = React.useRef(currentQueryParams);
  searchRef.current = search;
  currentQueryParamsRef.current = currentQueryParams;
  return {
          queryParams: currentQueryParams,
          setParams: React.useMemo((function () {
                  return function (param, param$1, param$2, param$3, param$4) {
                    var navigationMode_ = param$2 !== undefined ? param$2 : /* Push */0;
                    var removeNotControlledParams = param$3 !== undefined ? param$3 : true;
                    var newParams = Curry._1(param, currentQueryParamsRef.current);
                    if (param$1 !== undefined) {
                      Curry._1(param$1, newParams);
                    }
                    return setQueryParams(newParams, searchRef.current, navigationMode_, removeNotControlledParams, history, undefined);
                  };
                }), [])
        };
}

export {
  makeLink ,
  isRouteActive ,
  useIsRouteActive ,
  useActiveSubRoute ,
  makeRouteKey ,
  makePrepareProps ,
  parseQueryParams ,
  makeQueryParams ,
  setQueryParams ,
  useQueryParams ,
  
}
/* react Not a pure module */
