// Generated by ReScript, PLEASE EDIT WITH CARE


var Active = {
  Route: undefined
};

var Inactive = {
  Route: undefined
};

var Single = {
  Route: undefined
};

var Todos = {
  Route: undefined,
  Active: Active,
  Inactive: Inactive,
  Single: Single
};

var Single$1 = {
  Route: undefined
};

var Users = {
  Route: undefined,
  Single: Single$1
};

var Root = {
  Route: undefined,
  Todos: Todos,
  Users: Users
};

var OrgDeep = {
  Route: undefined
};

export {
  Root ,
  OrgDeep ,
  
}
/* No side effect */
