// @generated
// This file is autogenerated from `todoRoutes.json`, do not edit manually.
@live
let makeLink = (~datePeriod: option<DatePeriod.t>=?, ~statuses: option<array<TodoStatus.t>>=?, ()) => {
  open RelayRouter__Bindings
  let queryParams = QueryParams.make()
  switch datePeriod {
    | None => ()
    | Some(datePeriod) => queryParams->QueryParams.setParam(~key="datePeriod", ~value=datePeriod->DatePeriod.serialize->Js.Global.encodeURIComponent)
  }

  switch statuses {
    | None => ()
    | Some(statuses) => queryParams->QueryParams.setParam(~key="statuses", ~value=statuses->Belt.Array.map(value => value->TodoStatus.serialize->Js.Global.encodeURIComponent)->Js.Array2.joinWith(","))
  }
  `/todos/active${queryParams->QueryParams.toString}`
}

@inline
let routePattern = "/todos/active"

@live
let isRouteActive = ({pathname}: RelayRouter__Bindings.History.location, ~exact: bool=false, ()): bool => {
  RelayRouter__Internal.matchPathWithOptions({"path": routePattern, "end": exact}, pathname)->Belt.Option.isSome
}

@live
let useIsRouteActive = (~exact=false, ()) => {
  let location = RelayRouterUtils.useLocation()
  React.useMemo1(() => isRouteActive(location, ~exact, ()), [location])
}

@live
type prepareProps = {
  environment: RescriptRelay.Environment.t,
  location: RelayRouter__Bindings.History.location,
  datePeriod: option<DatePeriod.t>,
  statuses: option<array<TodoStatus.t>>,
}

let makeRouteKey = (
  ~pathParams: Js.Dict.t<string>,
  ~queryParams: RelayRouter__Bindings.QueryParams.t
): string => {
  ignore(pathParams)

  "Root__Todos__Active:"

    ++ queryParams->RelayRouter__Bindings.QueryParams.getParamByKey("datePeriod")->Belt.Option.getWithDefault("")
    ++ queryParams->RelayRouter__Bindings.QueryParams.getParamByKey("statuses")->Belt.Option.getWithDefault("")
}

@live
let makePrepareProps = (. 
  ~environment: RescriptRelay.Environment.t,
  ~pathParams: Js.Dict.t<string>,
  ~queryParams: RelayRouter__Bindings.QueryParams.t,
  ~location: RelayRouter__Bindings.History.location,
): prepareProps => {
  ignore(pathParams)
  {
    environment: environment,

    location: location,
    datePeriod: queryParams->RelayRouter__Bindings.QueryParams.getParamByKey("datePeriod")->Belt.Option.flatMap(value => value->Js.Global.decodeURIComponent->DatePeriod.parse),
    statuses: queryParams->RelayRouter__Bindings.QueryParams.getArrayParamByKey("statuses")->Belt.Option.map(value => value->Belt.Array.keepMap(value => value->Js.Global.decodeURIComponent->TodoStatus.parse)),
  }
}

@live
type renderProps<'prepared> = {
  childRoutes: React.element,
  prepared: 'prepared,
  environment: RescriptRelay.Environment.t,
  location: RelayRouter__Bindings.History.location,
  datePeriod: option<DatePeriod.t>,
  statuses: option<array<TodoStatus.t>>,
}

@live
type renderers<'prepared> = {
  prepare: prepareProps => 'prepared,
  prepareCode: option<(. prepareProps) => array<RelayRouterTypes.preloadAsset>>,
  render: renderProps<'prepared> => React.element,
}

@obj
external makeRenderer: (
  ~prepare: prepareProps => 'prepared,
  ~prepareCode: prepareProps => array<RelayRouterTypes.preloadAsset>=?,
  ~render: renderProps<'prepared> => React.element,
  unit
) => renderers<'prepared> = ""

type queryParams = {
  datePeriod: option<DatePeriod.t>,
  statuses: option<array<TodoStatus.t>>,
}

@live
let parseQueryParams = (search: string): queryParams => {
  open RelayRouter__Bindings
  let queryParams = QueryParams.parse(search)
  {
    datePeriod: queryParams->QueryParams.getParamByKey("datePeriod")->Belt.Option.flatMap(value => value->Js.Global.decodeURIComponent->DatePeriod.parse),

    statuses: queryParams->QueryParams.getArrayParamByKey("statuses")->Belt.Option.map(value => value->Belt.Array.keepMap(value => value->Js.Global.decodeURIComponent->TodoStatus.parse)),

  }
}

@live
let makeQueryParams = (
  ~datePeriod: option<DatePeriod.t>=?, 
  ~statuses: option<array<TodoStatus.t>>=?, 
  ()
) => {
  datePeriod: datePeriod,
  statuses: statuses,
}

@live
let setQueryParams = (
  newParams: queryParams,
  ~currentSearch: string, 
  ~navigationMode_=RelayRouterTypes.Push,
  ~removeNotControlledParams=true,
  ~history: RelayRouter__Bindings.History.t,
  ()
) => {
  open RelayRouter__Bindings

  let queryParams = if removeNotControlledParams {
    QueryParams.make()
  } else {
    QueryParams.parse(currentSearch)
  }

  
  queryParams->QueryParams.setParamOpt(~key="datePeriod", ~value=newParams.datePeriod->Belt.Option.map(datePeriod => datePeriod->DatePeriod.serialize->Js.Global.encodeURIComponent))
  queryParams->QueryParams.setParamOpt(~key="statuses", ~value=newParams.statuses->Belt.Option.map(statuses => statuses->Belt.Array.map(value => value->TodoStatus.serialize->Js.Global.encodeURIComponent)->Js.Array2.joinWith(",")))
  
  queryParams->RelayRouter__Internal.setQueryParams(navigationMode_, history)
}

@live
type useQueryParamsReturn = {
  queryParams: queryParams,
  setParams: (
    ~setter: queryParams => queryParams,
    ~onAfterParamsSet: queryParams => unit=?,
    ~navigationMode_: RelayRouterTypes.setQueryParamsMode=?,
    ~removeNotControlledParams: bool=?,
    unit
  ) => unit
}

@live
let useQueryParams = (): useQueryParamsReturn => {
  let {history} = RelayRouter.useRouterContext()
  let {search} = RelayRouterUtils.useLocation()
  let currentQueryParams = React.useMemo1(() => {
    search->parseQueryParams
  }, [search])

  let searchRef = React.useRef(search)
  let currentQueryParamsRef = React.useRef(currentQueryParams)

  searchRef.current = search
  currentQueryParamsRef.current = currentQueryParams

  {
    queryParams: currentQueryParams, 
    setParams: 
      React.useMemo0(
        () => (
          ~setter,
          ~onAfterParamsSet=?,
          ~navigationMode_=RelayRouterTypes.Push, 
          ~removeNotControlledParams=true,
          ()
        ) => {
          let newParams = setter(currentQueryParamsRef.current)

          switch onAfterParamsSet {
            | None => ()
            | Some(onAfterParamsSet) => onAfterParamsSet(newParams)
          }

          newParams
            ->setQueryParams(
              ~currentSearch=searchRef.current, 
              ~navigationMode_, 
              ~removeNotControlledParams, 
              ~history, 
              ()
            )
          },
      )
  }
}