// @generated
// This file is autogenerated from `todoRoutes.json`, do not edit manually.
module Internal = {
  @live
  type prepareProps = {
    environment: RescriptRelay.Environment.t,
    location: RelayRouter.History.location,
  }

  @live
  type renderProps<'prepared> = {
    childRoutes: React.element,
    prepared: 'prepared,
    environment: RescriptRelay.Environment.t,
    location: RelayRouter.History.location,
  }

  @live
  type renderers<'prepared> = {
    prepare: prepareProps => 'prepared,
    prepareCode: option<(. prepareProps) => array<RelayRouter.Types.preloadAsset>>,
    render: renderProps<'prepared> => React.element,
  }
  @live
  let makePrepareProps = (.
    ~environment: RescriptRelay.Environment.t,
    ~pathParams: dict<string>,
    ~queryParams: RelayRouter.Bindings.QueryParams.t,
    ~location: RelayRouter.History.location,
  ): prepareProps => {
    ignore(pathParams)
    ignore(queryParams)
    {
      environment: environment,
      location: location,
    }
  }
}

@inline
let routePattern = "/home"

@live
let makeLink = () => {
  RelayRouter.Bindings.generatePath(routePattern, dict{})
}

@live
type target = unit

@live
let targetFromMatchedRoute = (
  matchedRoute: RelayRouter.Types.matchedRoute,
  ~queryParams: RelayRouter.Bindings.QueryParams.t,
): option<target> =>
  switch matchedRoute.routeName {
  | "Root__Home" =>
    ignore(queryParams)
    Some(())
  | _ => None
  }

@live
let targetFromLocation = (location: RelayRouter.History.location): option<target> => {
  let queryParams = RelayRouter.Bindings.QueryParams.parse(location.search)
  switch RelayRouter.Internal.matchPathWithOptions({"path": routePattern, "end": true}, location.pathname) {
  | Some({params}) =>
    targetFromMatchedRoute({
      routeName: "Root__Home",
      routeKey: "",
      pathParams: params,
      slots: [],
      outlet: None,
    }, ~queryParams)
  | None => None
  }
}

@live
let targetToPath = (_target: target): string => makeLink()

@live
let targetKey = targetToPath

@live
let targetRouteName = "Root__Home"

module Target = {
  @live
  type t =
    | Self(target)

  let fromMatchedRoute = (
    matchedRoute: RelayRouter.Types.matchedRoute,
    ~queryParams: RelayRouter.Bindings.QueryParams.t,
  ): option<t> =>
    switch matchedRoute.routeName {
    | "Root__Home" =>
      targetFromMatchedRoute(matchedRoute, ~queryParams)->Option.map(target =>
        Self(target)
      )
    | _ => None
    }

  let fromEntryWithQueryParams = (
    entry: RelayRouter.Types.currentRouterEntry,
    ~queryParams: RelayRouter.Bindings.QueryParams.t,
  ): option<t> =>
    switch entry.matchedRoutes->Array.toReversed->Array.get(0) {
    | Some(matchedRoute) => fromMatchedRoute(matchedRoute, ~queryParams)
    | None => None
    }

  let fromEntry = (entry: RelayRouter.Types.currentRouterEntry): option<t> =>
    fromEntryWithQueryParams(entry, ~queryParams=entry.queryParams)

  let useCurrent = (): option<t> => {
    let router = RelayRouter.useRouterContext()
    let location = RelayRouter.Utils.useLocation()
    let (entry, setEntry) = React.useState(() => router.get())

    React.useEffect(() => {
      let dispose = router.subscribe(nextEntry => setEntry(_ => nextEntry))
      Some(dispose)
    }, [router])

    React.useMemo(() => {
      let queryParams = RelayRouter.Bindings.QueryParams.parse(location.search)
      fromEntryWithQueryParams(entry, ~queryParams)
    }, (entry, location.search))
  }

  let fromLocation = (location: RelayRouter.History.location): option<t> =>
    switch targetFromLocation(location) {
    | Some(target) => Some(Self(target))
    | None =>
      None
    }

  let toPath = (target: t): string =>
    switch target {
    | Self(target) => targetToPath(target)
    }

  let key = toPath

  let routeName = (target: t): string =>
    switch target {
    | Self(_) => "Root__Home"
    }

}

@live
let isRouteActive = (~exact: bool=false, {pathname}: RelayRouter.History.location): bool => {
  RelayRouter.Internal.matchPathWithOptions({"path": routePattern, "end": exact}, pathname)->Option.isSome
}

@live
let useIsRouteActive = (~exact=false) => {
  let location = RelayRouter.Utils.useLocation()
  React.useMemo(() => location->isRouteActive(~exact), (location, exact))
}

@obj
external makeRenderer: (
  ~prepare: Internal.prepareProps => 'prepared,
  ~prepareCode: Internal.prepareProps => array<RelayRouter.Types.preloadAsset>=?,
  ~render: Internal.renderProps<'prepared> => React.element,
) => Internal.renderers<'prepared> = ""
