// @generated
// This file is autogenerated from `todoRoutes.json`, do not edit manually.
type queryParams = {
  statuses: option<array<TodoStatus.t>>,
  statusWithDefault: TodoStatus.t,
  byValue: option<string>,
}

module Internal = {
  let parseQueryParams = (queryParams: RelayRouter.Bindings.QueryParams.t): queryParams => {
    open RelayRouter.Bindings
    {
      statuses: queryParams->QueryParams.getArrayParamByKey("statuses")->Option.map(value => value->Array.filterMap(value => value->TodoStatus.parse)),
      statusWithDefault: queryParams->QueryParams.getParamByKey("statusWithDefault")->Option.flatMap(value => value->TodoStatus.parse)->Option.getOr(TodoStatus.defaultValue),
      byValue: queryParams->QueryParams.getParamByKey("byValue")->Option.flatMap(value => Some(value)),
    }
  }

  @live
  type childPathParams = {
    byStatus: option<[#"completed" | #"not-completed"]>,
    byStatusDecoded: option<TodoStatusPathParam.t>,
    todoId: option<string>,
  }

  @live
  type prepareProps = {
    environment: RescriptRelay.Environment.t,
    location: RelayRouter.History.location,
    ...queryParams,
    childParams: childPathParams,
  }

  @live
  type renderProps<'prepared> = {
    childRoutes: React.element,
    prepared: 'prepared,
    environment: RescriptRelay.Environment.t,
    location: RelayRouter.History.location,
    ...queryParams,
    childParams: childPathParams,
  }

  @live
  type renderers<'prepared> = {
    prepare: prepareProps => 'prepared,
    prepareCode: option<(. prepareProps) => array<RelayRouter.Types.preloadAsset>>,
    render: renderProps<'prepared> => React.element,
  }
  @live
  let makePrepareProps = (.
    ~environment: RescriptRelay.Environment.t,
    ~pathParams: dict<string>,
    ~queryParams: RelayRouter.Bindings.QueryParams.t,
    ~location: RelayRouter.History.location,
  ): prepareProps => {
    {
      environment: environment,
      location: location,
      childParams: Obj.magic(pathParams),
      statuses: queryParams->RelayRouter.Bindings.QueryParams.getArrayParamByKey("statuses")->Option.map(value => value->Array.filterMap(value => value->TodoStatus.parse)),
      statusWithDefault: queryParams->RelayRouter.Bindings.QueryParams.getParamByKey("statusWithDefault")->Option.flatMap(value => value->TodoStatus.parse)->Option.getOr(TodoStatus.defaultValue),
      byValue: queryParams->RelayRouter.Bindings.QueryParams.getParamByKey("byValue")->Option.flatMap(value => Some(value)),
    }
  }
}

@live
let applyQueryParams = (
  queryParams: RelayRouter__Bindings.QueryParams.t,
  ~newParams: queryParams,
) => {
  open RelayRouter__Bindings

  queryParams->QueryParams.setParamArrayOpt(~key="statuses", ~value=newParams.statuses->Option.map(statuses => statuses->Array.map(statuses => statuses->TodoStatus.serialize)))
  queryParams->QueryParams.setParamOpt(~key="statusWithDefault", ~value=newParams.statusWithDefault->TodoStatus.serialize === TodoStatus.defaultValue->TodoStatus.serialize ? None : newParams.statusWithDefault->TodoStatus.serialize->Some)
  queryParams->QueryParams.setParamOpt(~key="byValue", ~value=newParams.byValue->Option.map(byValue => byValue))
}

@live
type useQueryParamsReturn = {
  queryParams: queryParams,
  setParams: (
    ~setter: queryParams => queryParams,
    ~onAfterParamsSet: queryParams => unit=?,
    ~navigationMode_: RelayRouter.Types.setQueryParamsMode=?,
    ~removeNotControlledParams: bool=?,
    ~shallow: bool=?,
  ) => unit
}

@live
let useQueryParams = (): useQueryParamsReturn => {
  let {search: search__} = RelayRouter.Utils.useLocation()
  let queryParams__ = React.useMemo(() => RelayRouter.Bindings.QueryParams.parse(search__), [search__])
  let statuses = {
    let param = queryParams__->RelayRouter.Bindings.QueryParams.getArrayParamByKey("statuses")
    React.useMemo(() => param->Option.map(value => value->Array.filterMap(value => value->TodoStatus.parse)), [param->Option.getOr([])->Array.join(" | ")])
  }
  let statusWithDefault = {
    let param = queryParams__->RelayRouter.Bindings.QueryParams.getParamByKey("statusWithDefault")
    React.useMemo(() => param->Option.flatMap(value => value->TodoStatus.parse)->Option.getOr(TodoStatus.defaultValue), [param])
  }
  let byValue = {
    let param = queryParams__->RelayRouter.Bindings.QueryParams.getParamByKey("byValue")
    React.useMemo(() => param->Option.flatMap(value => Some(value)), [param])
  }
  let currentQueryParams = React.useMemo(() => {
    statuses: statuses,
    statusWithDefault: statusWithDefault,
    byValue: byValue
  }, [search__])

  {
    queryParams: currentQueryParams,
    setParams: RelayRouter__Internal.useSetQueryParams(~parseQueryParams=Internal.parseQueryParams, ~applyQueryParams),
  }
}

@inline
let routePattern = "/todos"

@live
let makeLink = (~statuses: option<array<TodoStatus.t>>=?, ~statusWithDefault: option<TodoStatus.t>=?, ~byValue: option<string>=?) => {
  open RelayRouter.Bindings
  let queryParams = QueryParams.make()
  switch statuses {
    | None => ()
    | Some(statuses) => queryParams->QueryParams.setParamArray(~key="statuses", ~value=statuses->Array.map(value => value->TodoStatus.serialize))
  }

  switch statusWithDefault {
    | None => ()
    | Some(statusWithDefault) => queryParams->QueryParams.setParamOpt(~key="statusWithDefault", ~value=statusWithDefault->TodoStatus.serialize === TodoStatus.defaultValue->TodoStatus.serialize ? None : statusWithDefault->TodoStatus.serialize->Some)
  }

  switch byValue {
    | None => ()
    | Some(byValue) => queryParams->QueryParams.setParam(~key="byValue", ~value=byValue)
  }
  RelayRouter.Bindings.generatePath(routePattern, dict{}) ++ queryParams->QueryParams.toString
}
@live
let makeLinkFromQueryParams = (queryParams: queryParams) => {
  makeLink(~statuses=?queryParams.statuses, ~statusWithDefault=queryParams.statusWithDefault, ~byValue=?queryParams.byValue, )
}

@live
let useMakeLinkWithPreservedPath = (): ((queryParams => queryParams) => string) => RelayRouter__Internal.useMakeLinkWithPreservedPath(~parseQueryParams=Internal.parseQueryParams, ~applyQueryParams)

@live
type target = {
  statuses: option<array<TodoStatus.t>>,
  statusWithDefault: TodoStatus.t,
  byValue: option<string>,
}

@live
let targetFromMatchedRoute = (
  matchedRoute: RelayRouter.Types.matchedRoute,
  ~queryParams: RelayRouter.Bindings.QueryParams.t,
): option<target> =>
  switch matchedRoute.routeName {
  | "Root__Todos" =>
    let decodedQueryParams = Internal.parseQueryParams(queryParams)
    Some({
      statuses: decodedQueryParams.statuses,
      statusWithDefault: decodedQueryParams.statusWithDefault,
      byValue: decodedQueryParams.byValue,
    })
  | _ => None
  }

@live
let targetFromLocation = (location: RelayRouter.History.location): option<target> => {
  let queryParams = RelayRouter.Bindings.QueryParams.parse(location.search)
  switch RelayRouter.Internal.matchPathWithOptions({"path": routePattern, "end": true}, location.pathname) {
  | Some({params}) =>
    targetFromMatchedRoute({
      routeName: "Root__Todos",
      routeKey: "",
      pathParams: params,
      slots: [],
      outlet: None,
    }, ~queryParams)
  | None => None
  }
}

@live
let targetToPath = (target: target): string =>
  makeLink(~statuses=?target.statuses, ~statusWithDefault=target.statusWithDefault, ~byValue=?target.byValue)

@live
let targetKey = targetToPath

@live
let targetRouteName = "Root__Todos"

module Target = {
  @live
  type t =
    | Self(target)
    | ByStatus(Route__Root__Todos__ByStatus_route.target)
    | ByStatusDecoded(Route__Root__Todos__ByStatusDecoded_route.target)
    | ByStatusDecoded__Child(Route__Root__Todos__ByStatusDecoded__Child_route.target)
    | ByStatusDecodedExtra(Route__Root__Todos__ByStatusDecodedExtra_route.target)
    | Single(Route__Root__Todos__Single_route.target)

  let fromMatchedRoute = (
    matchedRoute: RelayRouter.Types.matchedRoute,
    ~queryParams: RelayRouter.Bindings.QueryParams.t,
  ): option<t> =>
    switch matchedRoute.routeName {
    | "Root__Todos" =>
      targetFromMatchedRoute(matchedRoute, ~queryParams)->Option.map(target =>
        Self(target)
      )
    | "Root__Todos__ByStatus" =>
      Route__Root__Todos__ByStatus_route.targetFromMatchedRoute(matchedRoute, ~queryParams)->Option.map(target =>
        ByStatus(target)
      )
    | "Root__Todos__ByStatusDecoded" =>
      Route__Root__Todos__ByStatusDecoded_route.targetFromMatchedRoute(matchedRoute, ~queryParams)->Option.map(target =>
        ByStatusDecoded(target)
      )
    | "Root__Todos__ByStatusDecoded__Child" =>
      Route__Root__Todos__ByStatusDecoded__Child_route.targetFromMatchedRoute(matchedRoute, ~queryParams)->Option.map(target =>
        ByStatusDecoded__Child(target)
      )
    | "Root__Todos__ByStatusDecodedExtra" =>
      Route__Root__Todos__ByStatusDecodedExtra_route.targetFromMatchedRoute(matchedRoute, ~queryParams)->Option.map(target =>
        ByStatusDecodedExtra(target)
      )
    | "Root__Todos__Single" =>
      Route__Root__Todos__Single_route.targetFromMatchedRoute(matchedRoute, ~queryParams)->Option.map(target =>
        Single(target)
      )
    | _ => None
    }

  let fromEntryWithQueryParams = (
    entry: RelayRouter.Types.currentRouterEntry,
    ~queryParams: RelayRouter.Bindings.QueryParams.t,
  ): option<t> =>
    switch entry.matchedRoutes->Array.toReversed->Array.get(0) {
    | Some(matchedRoute) => fromMatchedRoute(matchedRoute, ~queryParams)
    | None => None
    }

  let fromEntry = (entry: RelayRouter.Types.currentRouterEntry): option<t> =>
    fromEntryWithQueryParams(entry, ~queryParams=entry.queryParams)

  let useCurrent = (): option<t> => {
    let router = RelayRouter.useRouterContext()
    let location = RelayRouter.Utils.useLocation()
    let (entry, setEntry) = React.useState(() => router.get())

    React.useEffect(() => {
      let dispose = router.subscribe(nextEntry => setEntry(_ => nextEntry))
      Some(dispose)
    }, [router])

    React.useMemo(() => {
      let queryParams = RelayRouter.Bindings.QueryParams.parse(location.search)
      fromEntryWithQueryParams(entry, ~queryParams)
    }, (entry, location.search))
  }

  let fromLocation = (location: RelayRouter.History.location): option<t> =>
    switch targetFromLocation(location) {
    | Some(target) => Some(Self(target))
    | None =>
      switch Route__Root__Todos__ByStatus_route.targetFromLocation(location) {
      | Some(target) => Some(ByStatus(target))
      | None =>
        switch Route__Root__Todos__ByStatusDecoded_route.targetFromLocation(location) {
        | Some(target) => Some(ByStatusDecoded(target))
        | None =>
          switch Route__Root__Todos__ByStatusDecoded__Child_route.targetFromLocation(location) {
          | Some(target) => Some(ByStatusDecoded__Child(target))
          | None =>
            switch Route__Root__Todos__ByStatusDecodedExtra_route.targetFromLocation(location) {
            | Some(target) => Some(ByStatusDecodedExtra(target))
            | None =>
              switch Route__Root__Todos__Single_route.targetFromLocation(location) {
              | Some(target) => Some(Single(target))
              | None =>
                None
              }
            }
          }
        }
      }
    }

  let toPath = (target: t): string =>
    switch target {
    | Self(target) => targetToPath(target)
    | ByStatus(target) => Route__Root__Todos__ByStatus_route.targetToPath(target)
    | ByStatusDecoded(target) => Route__Root__Todos__ByStatusDecoded_route.targetToPath(target)
    | ByStatusDecoded__Child(target) => Route__Root__Todos__ByStatusDecoded__Child_route.targetToPath(target)
    | ByStatusDecodedExtra(target) => Route__Root__Todos__ByStatusDecodedExtra_route.targetToPath(target)
    | Single(target) => Route__Root__Todos__Single_route.targetToPath(target)
    }

  let key = toPath

  let routeName = (target: t): string =>
    switch target {
    | Self(_) => "Root__Todos"
    | ByStatus(_) => "Root__Todos__ByStatus"
    | ByStatusDecoded(_) => "Root__Todos__ByStatusDecoded"
    | ByStatusDecoded__Child(_) => "Root__Todos__ByStatusDecoded__Child"
    | ByStatusDecodedExtra(_) => "Root__Todos__ByStatusDecodedExtra"
    | Single(_) => "Root__Todos__Single"
    }

}

@live
let isRouteActive = (~exact: bool=false, {pathname}: RelayRouter.History.location): bool => {
  RelayRouter.Internal.matchPathWithOptions({"path": routePattern, "end": exact}, pathname)->Option.isSome
}

@live
let useIsRouteActive = (~exact=false) => {
  let location = RelayRouter.Utils.useLocation()
  React.useMemo(() => location->isRouteActive(~exact), (location, exact))
}
@live
type subRoute = [#ByStatus | #ByStatusDecoded | #ByStatusDecodedExtra | #Single]

@live
let getActiveSubRoute = (location: RelayRouter.History.location): option<[#ByStatus | #ByStatusDecoded | #ByStatusDecodedExtra | #Single]> => {
  let {pathname} = location
  if RelayRouter.Internal.matchPath("/todos/:byStatus(completed|not-completed)", pathname)->Option.isSome {
      Some(#ByStatus)
    } else if RelayRouter.Internal.matchPath("/todos/:byStatusDecoded", pathname)->Option.isSome {
      Some(#ByStatusDecoded)
    } else if RelayRouter.Internal.matchPath("/todos/extra/:byStatusDecoded", pathname)->Option.isSome {
      Some(#ByStatusDecodedExtra)
    } else if RelayRouter.Internal.matchPath("/todos/:todoId", pathname)->Option.isSome {
      Some(#Single)
    } else {
    None
  }
}

@live
let useActiveSubRoute = (): option<[#ByStatus | #ByStatusDecoded | #ByStatusDecodedExtra | #Single]> => {
  let location = RelayRouter.Utils.useLocation()
  React.useMemo(() => {
    getActiveSubRoute(location)
  }, [location])
}

@obj
external makeRenderer: (
  ~prepare: Internal.prepareProps => 'prepared,
  ~prepareCode: Internal.prepareProps => array<RelayRouter.Types.preloadAsset>=?,
  ~render: Internal.renderProps<'prepared> => React.element,
) => Internal.renderers<'prepared> = ""

@live
let parseRoute: (
  string,
  ~exact: bool=?,
) => option<queryParams> = RelayRouter.Internal.parseRoute(
  QueryParams({
    routePattern,
    parseQueryParams: Internal.parseQueryParams,
  }),
)
