// Generated by ReScript, PLEASE EDIT WITH CARE

import * as U from "../utils/U.mjs";
import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function Avatar(Props) {
  var content = Props.content;
  var title = Props.title;
  var sizeOpt = Props.size;
  var size = sizeOpt !== undefined ? sizeOpt : /* Medium */1;
  var tmp;
  switch (size) {
    case /* Large */0 :
        tmp = "w-14 h-14 text-2xl";
        break;
    case /* Medium */1 :
        tmp = "w-12 h-12 text-lg";
        break;
    case /* Small */2 :
        tmp = "w-10 h-10";
        break;
    
  }
  var className = U.tw([
        "rounded-full shadow-lg bg-blue-500",
        tmp
      ]);
  var tmp$1;
  tmp$1 = content.TAG === /* Image */0 ? "" : className;
  var tmp$2 = {
    className: U.tw([
          "relative inline-flex items-center justify-center",
          tmp$1
        ])
  };
  if (title !== undefined) {
    tmp$2.title = Caml_option.valFromOption(title);
  }
  var tmp$3;
  tmp$3 = content.TAG === /* Image */0 ? React.createElement("img", {
          className: className,
          alt: content.alt,
          src: content.src
        }) : React.createElement("span", {
          className: "font-medium leading-none text-white"
        }, content.text);
  return React.createElement("span", tmp$2, tmp$3);
}

var make = Avatar;

export {
  make ,
  
}
/* react Not a pure module */
