// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function TodosList(Props) {
  return React.createElement("div", {
              style: {
                backgroundColor: "tomato",
                display: "flex",
                height: "1500px",
                alignItems: "flex-end"
              }
            }, "List!");
}

var make = TodosList;

export {
  make ,
  
}
/* react Not a pure module */
