// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as RelaySSRUtils from "../../router/RelaySSRUtils.mjs";

function fetchQuery(param, param$1, param$2, param$3) {
  return RelaySSRUtils.makeClientFetchFunction((function (sink, operation, variables, _cacheConfig, _uploads) {
                fetch("http://localhost:4000/graphql", {
                          method: "POST",
                          headers: Js_dict.fromArray([[
                                  "content-type",
                                  "application/json"
                                ]]),
                          body: Belt_Option.getWithDefault(JSON.stringify({
                                    query: operation.text,
                                    variables: variables
                                  }), "")
                        }).then(function (r) {
                        return r.json();
                      }).then(function (json) {
                      sink.next(json);
                      return sink.complete();
                    });
                
              }), param, param$1, param$2, param$3);
}

function makeServerFetchQuery(onResponseReceived) {
  return function (param, param$1, param$2, param$3) {
    return RelaySSRUtils.makeServerFetchFunction(onResponseReceived, (function (sink, operation, variables, _cacheConfig, _uploads) {
                  fetch("http://localhost:4000/graphql", {
                            method: "POST",
                            headers: Js_dict.fromArray([[
                                    "content-type",
                                    "application/json"
                                  ]]),
                            body: Belt_Option.getWithDefault(JSON.stringify({
                                      query: operation.text,
                                      variables: variables
                                    }), "")
                          }).then(function (r) {
                          return r.json();
                        }).then(function (json) {
                        sink.next(json);
                        sink.complete();
                        return Promise.resolve(undefined);
                      });
                  
                }), param, param$1, param$2, param$3);
  };
}

export {
  fetchQuery ,
  makeServerFetchQuery ,
  
}
/* RelaySSRUtils Not a pure module */
