// Generated by ReScript, PLEASE EDIT WITH CARE


function tw(classes) {
  return classes.filter(function (c) {
                return c !== "";
              }).join(" ");
}

export {
  tw ,
  
}
/* No side effect */
