// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RelayRouter from "../router/RelayRouter.mjs";
import * as RelaySSRUtils from "../router/RelaySSRUtils.mjs";
import * as PendingIndicatorBar from "./components/PendingIndicatorBar.mjs";
import * as RescriptReactErrorBoundary from "@rescript/react/src/RescriptReactErrorBoundary.mjs";

if (!RelaySSRUtils.ssr) {
  window.history.scrollRestoration = "manual";
}

function App(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(RescriptReactErrorBoundary.make, {
                  children: React.createElement(RelayRouter.RouteRenderer.make, {
                        renderPending: (function (pending) {
                            return React.createElement(PendingIndicatorBar.make, {
                                        pending: pending
                                      });
                          }),
                        renderFallback: (function (param) {
                            return "Fallback...";
                          })
                      }),
                  fallback: (function (param) {
                      return "Error!";
                    })
                }));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
