// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.mjs";
import * as React from "react";
import * as RelayRouter from "../router/RelayRouter.mjs";
import * as RescriptRelay from "rescript-relay/src/RescriptRelay.mjs";
import * as RescriptReactErrorBoundary from "@rescript/react/src/RescriptReactErrorBoundary.mjs";

function Main(Props) {
  var environment = Props.environment;
  var routerContext = Props.routerContext;
  return React.createElement(RescriptRelay.Context.Provider.make, {
              environment: environment,
              children: React.createElement(RelayRouter.Provider.make, RelayRouter.Provider.makeProps(routerContext, React.createElement(React.Suspense, {
                            children: React.createElement(RescriptReactErrorBoundary.make, {
                                  children: React.createElement(App.make, {}),
                                  fallback: (function (param) {
                                      return "Error!";
                                    })
                                }),
                            fallback: "Loading..."
                          }), undefined))
            });
}

var make = Main;

export {
  make ,
  
}
/* App Not a pure module */
