// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NetworkUtils from "./utils/NetworkUtils.mjs";
import * as RescriptRelay from "rescript-relay/src/RescriptRelay.mjs";
import * as RelayRuntime from "relay-runtime";

var network = RelayRuntime.Network.create(NetworkUtils.fetchQuery, undefined);

function makeEnvironmentWithNetwork(network, missingFieldHandlers, param) {
  return RescriptRelay.Environment.make(network, RescriptRelay.Store.make(new RelayRuntime.RecordSource(undefined), 50, 21600000, undefined), undefined, undefined, missingFieldHandlers, undefined, undefined);
}

var environment = makeEnvironmentWithNetwork(network, undefined, undefined);

function makeServer(onResponseReceived) {
  var network = RelayRuntime.Network.create(NetworkUtils.makeServerFetchQuery(onResponseReceived), undefined);
  return makeEnvironmentWithNetwork(network, undefined, undefined);
}

export {
  network ,
  makeEnvironmentWithNetwork ,
  environment ,
  makeServer ,
  
}
/* network Not a pure module */
