// Generated by ReScript, PLEASE EDIT WITH CARE


function parse(str) {
  switch (str) {
    case "active" :
        return "active";
    case "inactive" :
        return "inactive";
    default:
      return ;
  }
}

function serialize(t) {
  return t;
}

export {
  parse ,
  serialize ,
  
}
/* No side effect */
