############################################################################
# Automated versioning and release using a changesets powered pull request #
############################################################################
name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: yarn

      - name: Use npm with trusted publishing support
        run: npm install -g npm@^11.5.1

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Provide release error log
        if: ${{ failure() }}
        run: cat /home/runner/.npm/_logs/*.log || echo "No log found"
